# Generated by Django 3.1.5 on 2021-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('nationalCode', models.PositiveIntegerField()),
                ('personalCode', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=200)),
                ('maritialStatus', models.BooleanField()),
                ('age', models.PositiveSmallIntegerField()),
                ('income', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
