# Generated by Django 3.1.5 on 2021-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210214_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='maritialStatus',
            field=models.CharField(max_length=7),
        ),
    ]
